### ISSUE TITLE
Evaluate, and store value in variable and "contain" conditional

### ISSUE THREAD

**Issue by TommyBs** [ihh/bracery#15]
I'm trying to follow the docs for the Bracery syntax, but finding it slightly confusing where it jumps to the (compatible) Tracery syntax when I want to use Bracery functionality.

Is the follow possible?

I want to expand a value into a variable and then use a conditional to check what sub variable is selected and act accordingly

e.g

```
let t = "$background=[#black#|#white#]\
$white=[white|yellow]\
$black=[black|navy]\
background is $background text color is  &if{&same{$background}{$black}}{white}{black}";

console.log(b.expand(t).text)

```
So if the background is one of the $white values I will use a black text color, and if it's one of the $white values use a black text color. Is this possible as it stands?

**Comment by ihh** [comment]
Thanks for the feedback @TommyBs.

The expansion of the alternation in the assignment of `$background` in your example will happen immediately (before `$black` or `$white` have been assigned); if you want it to be delayed, use `&quote` in front of the alternation where it's assigned, and then later indicate that you want to expand it (instead of just interpolating its value) by using `&eval$background` or just `&$background` for short.

~~~~
$background=&quote[#black#|#white#]
$white=[white|yellow]
$black=[black|navy]
background is &$background text color is &if{&same{$background}{$black}}{white}{black}
~~~~

Quoting an alternation is common enough that there is some syntactic sugar for it:
~~~~
[background=>#black#|#white#]
$white=[white|yellow]
$black=[black|navy]
background is &$background text color is &if{&same{$background}{$black}}{white}{black}
~~~~

You can also test these examples interactively by typing `bracery -r`, or by just pasting them into the online example, as e.g. [here](http://vega.biowiki.org/bracery/web/demo.html#%24background%3D%26quote%5B%23black%23%7C%23white%23%5D%0A%24white%3D%5Bwhite%7Cyellow%5D%0A%24black%3D%5Bblack%7Cnavy%5D%0Abackground%20is%20%26%24background%20text%20color%20is%20%26if%7B%26same%7B%24background%7D%7B%24black%7D%7D%7Bwhite%7D%7Bblack%7D%0A%0A%0A%5Bbackground2%3D%3E%23black%23%7C%23white%23%5D%0A%24white2%3D%5Bwhite%7Cyellow%5D%0A%24black2%3D%5Bblack%7Cnavy%5D%0Abackground2%20is%20%23background2%23%20text%20color%20is%20%26if%7B%26same%7B%24background2%7D%7B%24black2%7D%7D%7Bwhite%7D%7Bblack%7D%0A%0A).

**Comment by ihh** [comment]
Hmm, I'm now thinking I didn't read your example carefully enough. I think maybe what you want is actually to just move the assignment of `$background` after the assignment of `$black`:

~~~~
$white=[white|yellow]
$black=[black|navy]
$background=[#black#|#white#]
background is $background text color is &if{&same{$background}{$black}}{white}{black}
~~~~

This is demo'd [here](http://vega.biowiki.org/bracery/web/demo.html#%24white%3D%5Bwhite%7Cyellow%5D%0A%24black%3D%5Bblack%7Cnavy%5D%0A%24background%3D%5B%23black%23%7C%23white%23%5D%0Abackground%20is%20%24background%20text%20color%20is%20%26if%7B%26same%7B%24background%7D%7B%24black%7D%7D%7Bwhite%7D%7Bblack%7D). The way I had it before, it will occasionally say "background is black text color is black" because the value of the variable `$background` is `[#black#|#white#]`.

Another way would be [like this](http://vega.biowiki.org/bracery/web/demo.html#%24background_generator%3D%26quote%5B%23black%23%7C%23white%23%5D%0A%24white%3D%5Bwhite%7Cyellow%5D%0A%24black%3D%5Bblack%7Cnavy%5D%0A%24background%3D%26%24background_generator%0Abackground%20is%20%24background%20text%20color%20is%20%26if%7B%26same%7B%24background%7D%7B%24black%7D%7D%7Bwhite%7D%7Bblack%7D):

~~~~
$background_generator=&quote[#black#|#white#]
$white=[white|yellow]
$black=[black|navy]
$background=&$background_generator
background is $background text color is &if{&same{$background}{$black}}{white}{black}

**Comment by ihh** [comment]
It's hard to answer this without knowing a bit more specifically what you're trying to do - but the general idea is that Bracery variables contain text, and that text can itself be Bracery (which can be dynamically expanded with `&$variable_name`, `#variable_name#`, or `&eval$variable_name`)

There are a few different ways to write things - but that's the basic idea - text and Bracery code are the same thing, so "creating a function" is basically quoting, "calling a function" is evaluation and expansion of the quoted text as Bracery code in the current context, and so on.

Marking as closed but happy to continue discussing ---
